# Generated by Django 5.2.7 on 2025-10-08 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(help_text='Path/key in S3', max_length=255, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_s3_key',
            field=models.CharField(blank=True, help_text='If provided, overrides default avatar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.defaultavatar'),
        ),
    ]
