# Generated by Django 5.2.7 on 2025-10-08 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_defaultavatar_profile_avatar_s3_key_and_more'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='themes.theme'),
        ),
    ]
