# Generated by Django 5.2.7 on 2026-02-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Thumbnail/preview image for theme selection', null=True, upload_to='themes/previews/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='svg_file',
            field=models.FileField(blank=True, help_text='SVG pattern file for the theme background', null=True, upload_to='themes/svg/'),
        ),
    ]
