# Generated by Django 5.2.7 on 2025-10-08 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='lowercase, no #', max_length=64, unique=True)),
                ('slug', models.SlugField(help_text='url-safe', max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='tags_hashta_name_17e303_idx'), models.Index(fields=['slug'], name='tags_hashta_slug_af7958_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hashtags', to='tags.hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hashtags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'hashtag'], name='tags_userha_user_id_46c26e_idx'), models.Index(fields=['hashtag'], name='tags_userha_hashtag_e150b2_idx')],
                'unique_together': {('user', 'hashtag')},
            },
        ),
    ]
