# Generated by Django 5.2.7 on 2025-10-03 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['order_index', 'title']},
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cover_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_portfolios', to='portfolios.page'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pages_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='privacy',
            field=models.CharField(choices=[('draft', 'Draft'), ('link_only', 'Link-only'), ('public', 'Public')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'order_index'], name='portfolios__user_id_c7928f_idx'),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='font',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='theme_color',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='visibility',
        ),
    ]
