# Generated by Django 5.2.7 on 2025-10-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_portfolio_options_rename_owner_portfolio_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
