# Generated by Django 5.2.7 on 2025-10-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_page_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagemedia',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pagemedia',
            constraint=models.UniqueConstraint(fields=('page', 'media'), name='uniq_page_media'),
        ),
        migrations.AddConstraint(
            model_name='pagemedia',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='uniq_page_order'),
        ),
    ]
