# Generated by Django 5.2.7 on 2025-10-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_pagemedia_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolios__user_id_c7928f_idx',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
