# Generated by Django 5.2.7 on 2025-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_remove_portfolio_portfolios__user_id_c7928f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pagemedia',
            name='uniq_page_media',
        ),
        migrations.RemoveConstraint(
            model_name='pagemedia',
            name='uniq_page_order',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pages_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('portfolio', 'order'), name='uniq_page_order_per_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='pagemedia',
            constraint=models.UniqueConstraint(fields=('page', 'media'), name='uniq_page_media_pair'),
        ),
        migrations.AddConstraint(
            model_name='pagemedia',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='uniq_page_media_order'),
        ),
    ]
