# Generated by Django 5.2.7 on 2025-11-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_remove_pagemedia_uniq_page_media_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='page',
            name='uniq_page_order_per_portfolio',
        ),
        migrations.AddField(
            model_name='page',
            name='media_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_pages/'),
        ),
        migrations.AddField(
            model_name='page',
            name='media_shape',
            field=models.CharField(choices=[('1:1', 'Square (1:1)'), ('9:16', 'Vertical (9:16)'), ('16:9', 'Wide (16:9)'), ('4:5', 'Vertical (4:5)'), ('5:4', 'Wide (5:4)')], default='1:1', max_length=4),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=[('MediaLeft_TextRight', 'Media Left • Text Right'), ('MediaRight_TextLeft', 'Media Right • Text Left'), ('MediaTop_TextBottom', 'Media Top • Text Bottom'), ('MediaBottom_TextTop', 'Media Bottom • Text Top'), ('TextOnly', 'Text Only')], default='MediaLeft_TextRight', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
