# Generated by Django 5.2.7 on 2025-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=[('MediaLeft_TextRight', 'Media Left • Text Right'), ('MediaRight_TextLeft', 'Media Right • Text Left'), ('MediaTop_TextBottom', 'Media Top • Text Bottom'), ('MediaBottom_TextTop', 'Media Bottom • Text Top'), ('TextOnly', 'Text Only'), ('MediaOnly', 'MediaOnly')], default='MediaLeft_TextRight', max_length=50),
        ),
    ]
