# Generated by Django 5.2.7 on 2025-11-26 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_alter_page_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('draft', 'Draft'), ('link_only', 'Link-only'), ('public', 'Public')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_unpublished_changes', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('layout', models.CharField(choices=[('MediaLeft_TextRight', 'Media Left • Text Right'), ('MediaRight_TextLeft', 'Media Right • Text Left'), ('MediaTop_TextBottom', 'Media Top • Text Bottom'), ('MediaBottom_TextTop', 'Media Bottom • Text Top'), ('TextOnly', 'Text Only'), ('MediaOnly', 'MediaOnly')], default='MediaLeft_TextRight', max_length=50)),
                ('media_image', models.ImageField(blank=True, null=True, upload_to='draft_portfolio_pages/')),
                ('media_shape', models.CharField(choices=[('1:1', 'Square (1:1)'), ('9:16', 'Vertical (9:16)'), ('16:9', 'Wide (16:9)'), ('4:5', 'Vertical (4:5)'), ('5:4', 'Wide (5:4)')], default='1:1', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='portfolios.draftportfolio')),
            ],
        ),
    ]
