# Generated by Django 5.2.7 on 2025-11-29 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_draftportfolio_draftpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='draftportfolio',
            name='has_unpublished_changes',
        ),
        migrations.AlterField(
            model_name='draftpage',
            name='layout',
            field=models.CharField(choices=[('MediaLeft_TextRight', 'Media Left • Text Right'), ('MediaRight_TextLeft', 'Media Right • Text Left'), ('MediaTop_TextBottom', 'Media Top • Text Bottom'), ('MediaBottom_TextTop', 'Media Bottom • Text Top'), ('TextOnly', 'Text Only'), ('MediaOnly', 'Media Only')], default='MediaLeft_TextRight', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=[('MediaLeft_TextRight', 'Media Left • Text Right'), ('MediaRight_TextLeft', 'Media Right • Text Left'), ('MediaTop_TextBottom', 'Media Top • Text Bottom'), ('MediaBottom_TextTop', 'Media Bottom • Text Top'), ('TextOnly', 'Text Only'), ('MediaOnly', 'Media Only')], default='MediaLeft_TextRight', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_portfolio_slug'),
        ),
    ]
