# Generated by Django 5.2.7 on 2025-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_alter_portfolio_slug_alter_portfolio_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftportfolio',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False),
        ),
    ]
