# Generated by Django 5.2.7 on 2026-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_add_two_column_layouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpage',
            name='layout',
            field=models.CharField(choices=[('MediaLeft_TextRight', 'Media Left • Text Right'), ('MediaRight_TextLeft', 'Media Right • Text Left'), ('HeroLayoutSquare00', 'Title Page 1'), ('TwoColumnMediaOnly', 'Two Column Media Only'), ('TwoColumnMediaWithText', 'Two Column Media With Text'), ('TextOnly', 'Text Only'), ('MediaOnly', 'Media Only'), ('MediaTop_TextBottom', 'Media Top • Text Bottom'), ('MediaBottom_TextTop', 'Media Bottom • Text Top')], default='MediaLeft_TextRight', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=[('MediaLeft_TextRight', 'Media Left • Text Right'), ('MediaRight_TextLeft', 'Media Right • Text Left'), ('HeroLayoutSquare00', 'Title Page 1'), ('TwoColumnMediaOnly', 'Two Column Media Only'), ('TwoColumnMediaWithText', 'Two Column Media With Text'), ('TextOnly', 'Text Only'), ('MediaOnly', 'Media Only'), ('MediaTop_TextBottom', 'Media Top • Text Bottom'), ('MediaBottom_TextTop', 'Media Bottom • Text Top')], default='MediaLeft_TextRight', max_length=50),
        ),
    ]
